[env]
TERM = "xterm-256color"

[general]
import = [
    # uncomment the flavour you want below:
    #"~/.config/alacritty/catppuccin-latte.toml",
    #"~/.config/alacritty/catppuccin-frappe.toml",
    #"~/.config/alacritty/catppuccin-macchiato.toml",
    "~/.config/alacritty/catppuccin-mocha.toml",
]

[window]
blur          = true
opacity       = 0.9
option_as_alt = "Both"

[window.padding]
x = 10
y = 10

[font]
normal.family = "Hack Nerd Font Mono"
size          = 14
